# 数据库连接
# link = "mysql:zhang_ge:Dctp@zhang2020168@tcp(rr-j6cx3dyvmma17f0b6eo.mysql.rds.aliyuncs.com:3306)/dcesys_b"
# link = "mysql:root:root123@tcp(localhost:3306)/user_relaction?"
[database]
link = "mysql:zhang_ge:Dctp@zhang2020168@tcp(rr-j6cx3dyvmma17f0b6eo.mysql.rds.aliyuncs.com:3306)/dcesys_b"